export const friendlyAccessLabels = {
  nl: {
    frameTitle: "URL van je app en login",
    frameDescription: "Geef Specwright de URL waar de test moet starten. Voeg alleen login toe als deze test dat nodig heeft.",
    websiteTitle: "Vul de URL van je app in",
    websiteDescription: "Plak de URL van de omgeving die je wilt testen. Dat mag test, acceptatie, productie of localhost zijn.",
    appLink: "URL van je app",
    appLinkHelp: "Dit is de pagina die Specwright opent om de test te maken, bijvoorbeeld https://acceptatie.example.nl of http://localhost:4200.",
    appLinkAdded: "App-URL ingevuld",
    appLinkMissing: "App-URL ontbreekt",
    signInTitle: "Login kiezen",
    signInDescription: "Zet login alleen aan als de gebruiker eerst moet inloggen voor een scenario.",
    loginOn: "Login staat aan. Vul de testgebruiker in.",
    loginOff: "Login staat uit. Specwright opent de app direct.",
    loginDetails: "Logingegevens invullen",
    loginChoice: "Login",
    noLoginNeeded: "Geen login nodig",
    loginReady: "Logingegevens toegevoegd",
    loginMissing: "Logingegevens ontbreken",
    testWriter: "Test-AI",
    testWriterDescription: "OpenCode is de standaard voor lokaal werken. Pas dit alleen aan als je bewust een andere AI gebruikt.",
    nextReadyKicker: "Volgende stap",
    nextBlockedKicker: "Volgende actie",
    readyTitle: "Beschrijf je scenario's",
    readyDescription: "De benodigde gegevens staan klaar. Tijdens de run pauzeert Specwright als login of toegang niet lukt.",
    notReadyTitle: "Vul de URL van je app in",
    notReadyDescription: "Daarna kun je scenario's beschrijven en de test laten maken.",
    setupSummaryLabel: "Instellingen voor app-URL en login",
    addAppLinkFirst: "Vul eerst de URL van je app in.",
    addLoginFirst: "Vul eerst de logingegevens in of zet login uit.",
    nextButton: "Naar scenario's",
    readyToEdit: "Toegevoegd. Klik om aan te passen.",
    clickToFix: "Klik om dit aan te vullen.",
  },
  en: {
    frameTitle: "App URL and login",
    frameDescription: "Give Specwright the URL where the test should start. Add login only when this test needs it.",
    websiteTitle: "Add your app URL",
    websiteDescription: "Paste the URL for the environment you want to test. This can be test, staging, production, or localhost.",
    appLink: "App URL",
    appLinkHelp: "This is the page Specwright opens to create the test, for example https://staging.example.com or http://localhost:4200.",
    appLinkAdded: "App URL added",
    appLinkMissing: "App URL missing",
    signInTitle: "Choose login",
    signInDescription: "Turn on login only when the user must sign in for a scenario.",
    loginOn: "Login is on. Add the test user.",
    loginOff: "Login is off. Specwright opens the app directly.",
    loginDetails: "Add login details",
    loginChoice: "Login",
    noLoginNeeded: "No login needed",
    loginReady: "Login details added",
    loginMissing: "Login details missing",
    testWriter: "Test maker",
    testWriterDescription: "OpenCode is the default for local work. Only change this when you intentionally use another AI.",
    nextReadyKicker: "Next step",
    nextBlockedKicker: "Next action",
    readyTitle: "Describe scenarios",
    readyDescription: "The required details are in place. During the run, Specwright pauses if login or access fails.",
    notReadyTitle: "Add the app URL",
    notReadyDescription: "Then you can describe scenarios and let Specwright create the test.",
    setupSummaryLabel: "App URL and login settings",
    addAppLinkFirst: "Add your app URL first.",
    addLoginFirst: "Add login details first or turn login off.",
    nextButton: "Go to scenarios",
    readyToEdit: "Added. Click to edit.",
    clickToFix: "Click to complete this.",
  },
};

export const advancedLabels = {
  nl: {
    title: "Runvoorkeuren",
    description: "Bepaal hoe zichtbaar en debugbaar de test draait. Standaard blijft de browser verborgen.",
    autosaveHelp: "Wijzigingen worden direct opgeslagen.",
    openButton: "Runvoorkeuren",
    openDescription: "Browser, video, AI en goedkeuringen. Meestal kun je dit laten staan.",
    testRun: "Testuitvoering",
    showBrowser: "Browser zichtbaar openen",
    browserHidden: "Standaard: headless",
    browserVisible: "Browser opent zichtbaar.",
    timeout: "Maximale wachttijd per stap",
    timeoutHelp: "Hoe lang Specwright wacht voordat een stap faalt.",
    screenshots: "Screenshot bij fout",
    screenshotsHelp: "Laat zien waar de test vastloopt.",
    video: "Video-opname",
    videoHelp: "Handig bij visuele fouten.",
    tracing: "Trace bewaren",
    tracingHelp: "Voor diepere foutanalyse.",
    onFailure: "Bij fout",
    always: "Altijd",
    off: "Uit",
    aiConnection: "AI-verbinding",
    baseUrlPlaceholder: "Optioneel, bijv. http://localhost:11434/v1",
    apiKeyPlaceholder: "Optionele API-sleutel",
    sourcesAndApprovals: "Pauzes en akkoord",
    autoContinue: "Zonder pauzes doorgaan",
    autoContinueHelp: "Alleen als Specwright zelfstandig mag kiezen.",
    extraValues: "Extra projectwaarden",
    extraValuesHelp: "Projectspecifieke `.env` waarden buiten de standaardvelden.",
    show: "Toon",
    hide: "Verberg",
    valuePlaceholder: "waarde",
    add: "Toevoegen",
  },
  en: {
    title: "Run preferences",
    description: "Choose how visible and debuggable the test run should be. By default, the browser stays hidden.",
    autosaveHelp: "Changes are saved automatically.",
    openButton: "Run preferences",
    openDescription: "Browser, video, AI, and approvals. You can usually leave this as is.",
    testRun: "Test run",
    showBrowser: "Open browser visibly",
    browserHidden: "Default: headless",
    browserVisible: "Browser opens visibly.",
    timeout: "Maximum wait per step",
    timeoutHelp: "How long Specwright waits before a step fails.",
    screenshots: "Screenshot on failure",
    screenshotsHelp: "Shows where the test got stuck.",
    video: "Video recording",
    videoHelp: "Useful for visual failures.",
    tracing: "Save trace",
    tracingHelp: "For deeper failure analysis.",
    onFailure: "On failure",
    always: "Always",
    off: "Off",
    aiConnection: "AI connection",
    baseUrlPlaceholder: "Optional, e.g. http://localhost:11434/v1",
    apiKeyPlaceholder: "Optional API key",
    sourcesAndApprovals: "Pauses and approval",
    autoContinue: "Continue without pauses",
    autoContinueHelp: "Only when Specwright may decide independently.",
    extraValues: "Extra project values",
    extraValuesHelp: "Project-specific `.env` values outside the standard fields.",
    show: "Show",
    hide: "Hide",
    valuePlaceholder: "value",
    add: "Add",
  },
};

export type FriendlyAccessText = typeof friendlyAccessLabels.nl;
export type AdvancedAccessText = typeof advancedLabels.nl;
