// Auto-generated by Specwright — edit or regenerate via the UI
export default [
  {
    moduleName: '@TestGoal1',
    category: '@Modules',
    subModuleName: [],
    fileName: 'test-goal1',
    filePath: 'e2e-tests/data/migrations/files/SPECWRIGHT_README_FOR_TESTING.md',
    inputs: {},
    explore: true,
    runExploredCases: false,
    runGeneratedCases: false,
    autoApprove: false,
  }
];
