import type { PipelinePhase } from "./pipeline-types";

export const PIPELINE_PHASES: PipelinePhase[] = [
  {
    id: 1,
    label: "Config",
    description: "Read instructions.js",
    icon: "⚙️",
    color: "#3b82f6",
    glow: "shadow-blue-500/50",
    reads: "instructions.js",
    writes: "parsed config",
    agent: "input-processor",
  },
  {
    id: 2,
    label: "Validate",
    description: "Validate inputs",
    icon: "✅",
    color: "#3b82f6",
    glow: "shadow-blue-500/50",
    reads: "config object",
    writes: "validated config",
    agent: "input-validator",
  },
  {
    id: 3,
    label: "Plan",
    description: "Extract test plan",
    icon: "📋",
    color: "#3b82f6",
    glow: "shadow-blue-500/50",
    reads: "instructions",
    writes: "plan.md",
    agent: "plan-extractor",
  },
  {
    id: 4,
    label: "Explore",
    description: "Browser exploration",
    icon: "🌐",
    color: "#8b5cf6",
    glow: "shadow-purple-500/50",
    reads: "pageURL",
    writes: "seed.spec.js",
    agent: "playwright-test-planner",
  },
  {
    id: 5,
    label: "Seed",
    description: "Generate seed tests",
    icon: "🌱",
    color: "#8b5cf6",
    glow: "shadow-purple-500/50",
    reads: "plan + seed",
    writes: "seed test file",
    agent: "seed-generator",
  },
  {
    id: 6,
    label: "Approve",
    description: "Human review gate",
    icon: "👤",
    color: "#f59e0b",
    glow: "shadow-amber-500/50",
    reads: "plan + seed",
    writes: "approval",
    agent: "— you —",
    isGate: true,
  },
  {
    id: 7,
    label: "Generate",
    description: "BDD feature + steps",
    icon: "✍️",
    color: "#10b981",
    glow: "shadow-emerald-500/50",
    reads: "plan + seed",
    writes: ".feature + steps.js",
    agent: "bdd-generator + code-generator",
  },
  {
    id: 8,
    label: "Execute",
    description: "Run playwright tests",
    icon: "▶️",
    color: "#f97316",
    glow: "shadow-orange-500/50",
    reads: ".feature files",
    writes: "test results",
    agent: "execution-manager",
  },
  {
    id: 9,
    label: "Heal",
    description: "Auto-fix failures",
    icon: "🔧",
    color: "#f97316",
    glow: "shadow-orange-500/50",
    reads: "test errors",
    writes: "fixed steps",
    agent: "playwright-healer",
  },
  {
    id: 10,
    label: "Review",
    description: "Quality score report",
    icon: "⭐",
    color: "#eab308",
    glow: "shadow-yellow-500/50",
    reads: "all outputs",
    writes: "quality-report.md",
    agent: "quality-reviewer",
  },
];
